import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import AppNavigation from "@/components/AppNavigation";
import { ModeToggle } from "@/components/ui/mode-toggle";
import ResponsiveMenuDock from "@/components/ResponsiveMenuDock";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lora.variable} ${geistSans.variable} ${geistMono.variable}   antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className=" min-h-screen bg-background text-foreground">
            {/* Large screen navigation */}

            <AppNavigation />

            <div className="fixed top-4 right-4 z-50">
              <ModeToggle />
            </div>

            {/* Small screen navigation */}
            <ResponsiveMenuDock />
            <div className="max-w-3xl mx-auto">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
